version: '3.8'

services:
  rabbitmq:
    image: bitnami/rabbitmq:4.1.3
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true